apiVersion: v1
kind: Pod
metadata:
  name: dev
  labels:
    app: dev
spec:
  containers:
  - image: ghcr.io/robertorojas/proxmox_k8s_homelab/k8slab-dev:20240621
    imagePullPolicy: IfNotPresent
    name: dev
    ports:
    - containerPort: 22
    - containerPort: 80
    - containerPort: 8080
    volumeMounts:
    - name: authorizedkeys-volume
      mountPath: /root/.ssh/authorized_keys
      subPath: authorized_keys
      readOnly: true
    - name: sshkey-volume
      mountPath: /root/.ssh/id_rsa
      subPath: id_rsa
      readOnly: true
    - name: sshkey-pub-volume
      mountPath: /root/.ssh/id_rsa.pub
      subPath: id_rsa.pub
      readOnly: true
  restartPolicy: Always
  volumes:
  - name: authorizedkeys-volume
    configMap:
      name: authorizedkeys
  - name: sshkey-volume
    secret:
      secretName: sshkey
      defaultMode: 256
  - name: sshkey-pub-volume
    secret:
      secretName: sshkey-pub
      defaultMode: 256
