apiVersion: v1
kind: Service
metadata:
  name: dev
spec:
  selector:
    app: dev
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer